-- DB 스키마 생성
CREATE DATABASE IDOLDB;
-- DB권한 부여
GRANT ALL PRIVILEGES ON IDOLDB.* TO 'ohgiraffers'@'%';
-- DB 사용
use IDOLDB;

-- TABLE 삭제
-- DROP TABLE IDOL_GROUP;
-- DROP TABLE HITSONG; 

-- IDOL_GROUP TABLE 생성
CREATE TABLE `IDOL_GROUP`
(
 `GROUP_CODE`    INT AUTO_INCREMENT COMMENT '그룹코드',
`GROUP_NAME`    VARCHAR(30) COMMENT '그룹명',
`GROUP_COUNT`    INT COMMENT '그룹인원',
`ENT_NAME`    VARCHAR(30) COMMENT '소속사',
`HITSONG`    VARCHAR(30) COMMENT '히트곡명',
`FANDUM_NAME`    VARCHAR(30) COMMENT '팬덤명',
`DEB_YEAR`    VARCHAR(30) COMMENT '데뷔연도',
`DIS_YEAR`    VARCHAR(30) COMMENT '해체연도',
`DIS_YN`    CHAR(1) COMMENT '해체여부',
PRIMARY KEY ( `GROUP_CODE` )
) COMMENT = 'IDOL_GROUP';

ALTER TABLE `IDOL_GROUP`
ADD CONSTRAINT `IDOL_GROUP_PK` PRIMARY KEY ( `GROUP_CODE` );

-- HITSONG TABLE 생성
CREATE TABLE `HITSONG`
(
`HIT_CODE`    INT AUTO_INCREMENT COMMENT '히트곡 코드',
`GROUP_CODE`    INT COMMENT '그룹코드',
`HIT_NAME`    VARCHAR(100) COMMENT '히트송명',
`HIT_YEAR`    VARCHAR(30) COMMENT '히트연도',
`ALBUM_NAME`    VARCHAR(100) COMMENT '앨범명',
`TITLE_YN`    CHAR(1) COMMENT '타이틀곡 여부',
PRIMARY KEY ( `HIT_CODE` )
) COMMENT = 'HITSONG';

ALTER TABLE `HITSONG`
ADD CONSTRAINT `HITSONG_PK` PRIMARY KEY ( `HIT_CODE` );

-- 테이블 조회
SELECT * FROM IDOL_GROUP;
SELECT * FROM  HITSONG;


